package zet.kedzieri.usosztauth.ztapi;

import java.io.IOException;

public class ZTApiException extends IOException {

    public ZTApiException(String message, Throwable cause) {
        super(message, cause);
    }

}
